import io
import re
import typing
import wave
from os.path import join
from pathlib import Path
from threading import Lock

from mimic3_tts import AudioResult, Mimic3Settings, Mimic3TextToSpeechSystem, SSMLSpeaker
from ovos_plugin_manager.tts import TTS
from ovos_utils.xdg_utils import xdg_data_home


class Mimic3TTSPlugin(TTS):
    """Mycroft interface to Mimic3."""
    default_voices = {
        # TODO add default voice for every lang
        "en": "en_US/cmu-arctic_low",
        "en-uk": "en_UK/apope_low",
        "en-gb": "en_UK/apope_low",
        "de": "de_DE/thorsten_low",
        "bn": "bn/multi_low",
        "af": "af_ZA/google-nwu_low",
        "es": "es_ES/m-ailabs_low",
        "fa": "fa/haaniye_low",
        "fi": "fi_FI/harri-tapani-ylilammi_low",
        "fr": "fr_FR/m-ailabs_low",
        "it": "it_IT/mls_low",
        "ko": "ko_KO/kss_low",
        "nl": "nl/bart-de-leeuw_low",
        "pl": "pl_PL/m-ailabs_low",
        "ru": "ru_RU/multi_low",
        "uk": "uk_UK/m-ailabs_low"
    }

    def __init__(self, lang="en-us", config=None):
        super().__init__(lang, config)
        self.lock = Lock()
        self.lang = self.config.get("language") or self.lang
        preload_voices = self.config.get("preload_voices") or []
        preload_langs = self.config.get("preload_langs") or [self.lang]
        default_voice = self.config.get("voice")
        voice_dl = self.config.get("voices_download_dir") or join(xdg_data_home(), "mycroft", "mimic3", "voices")
        voice_dirs = self.config.get("voices_directories") or [voice_dl]

        self.tts = Mimic3TextToSpeechSystem(
            Mimic3Settings(
                voice=default_voice,
                language=self.lang,
                voices_directories=voice_dirs,
                voices_url_format=self.config.get("voices_url_format"),
                speaker=self.config.get("speaker"),
                length_scale=self.config.get("length_scale"),
                noise_scale=self.config.get("noise_scale"),
                noise_w=self.config.get("noise_w"),
                voices_download_dir=voice_dl,
                use_deterministic_compute=self.config.get(
                    "use_deterministic_compute", False
                ),
            )
        )

        if default_voice:
            self.default_voices[self.lang] = default_voice

        for voice in preload_voices:
            self.tts.preload_voice(voice)

        for lang in preload_langs:
            if lang not in self.default_voices:
                lang = lang.split("-")[0]
            voice = self.default_voices.get(lang)
            if voice:
                self.tts.preload_voice(voice)

    def get_tts(self, sentence, wav_file, lang=None, voice=None, speaker=None):
        """Synthesize audio using Mimic3 on device"""

        # support optional args for lang/voice/etc per request
        # a lock is used because we modify internal self.tts state
        with self.lock:
            def_speaker = self.tts.speaker
            def_voice = self.tts.voice
            if voice:
                self.tts.voice = voice
            elif lang:
                if lang not in self.default_voices:
                    lang = lang.split("-")[0]
                if lang in self.default_voices:
                    self.tts.voice = self.default_voices[lang]
            if speaker:
                self.tts.speaker = speaker

            # self.tts.settings.length_scale = length_scale
            # self.tts.settings.noise_scale = noise_scale
            # self.tts.settings.noise_w = noise_w

            sentence, ssml = self._apply_text_hacks(sentence)
            wav_bytes = self._mimic3_synth(sentence, ssml=ssml)

            self.tts.voice = def_voice
            self.tts.speaker = def_speaker

        # Write WAV to file
        Path(wav_file).write_bytes(wav_bytes)

        return (wav_file, None)

    @property
    def available_languages(self) -> set:
        """Return languages supported by this TTS implementation in this state
        This property should be overridden by the derived class to advertise
        what languages that engine supports.
        Returns:
            set: supported languages
        """
        return set(Mimic3TTSPluginConfig.keys())

    @staticmethod
    def _apply_text_hacks(sentence: str) -> typing.Tuple[str, bool]:
        """Mycroft-specific workarounds for text.

        Returns: (text, ssml)
        """

        # HACK: Mycroft gives "eight a.m.next sentence" sometimes
        sentence = sentence.replace(" a.m.", " a.m. ")
        sentence = sentence.replace(" p.m.", " p.m. ")

        # A I -> A.I.
        sentence = re.sub(
            r"\b([A-Z](?: |$)){2,}",
            lambda m: m.group(0).strip().replace(" ", ".") + ". ",
            sentence,
        )

        # Assume SSML if sentence begins with an angle bracket
        ssml = sentence.strip().startswith("<")

        # HACK: Speak single letters from Mycroft (e.g., "A;")
        if (len(sentence) == 2) and sentence.endswith(";"):
            letter = sentence[0]
            ssml = True
            sentence = f'<say-as interpret-as="spell-out">{letter}</say-as>'
        else:
            # HACK: 'A' -> spell out
            sentence, subs_made = re.subn(
                r"'([A-Z])'",
                r'<say-as interpret-as="spell-out">\1</say-as>',
                sentence,
            )
            if subs_made > 0:
                ssml = True

        return (sentence, ssml)

    def _mimic3_synth(self, text: str, ssml: bool = False) -> bytes:
        """Synthesize audio from text and return WAV bytes"""
        with io.BytesIO() as wav_io:
            wav_file: wave.Wave_write = wave.open(wav_io, "wb")
            wav_params_set = False

            with wav_file:
                try:
                    if ssml:
                        # SSML
                        results = SSMLSpeaker(self.tts).speak(text)
                    else:
                        # Plain text
                        self.tts.begin_utterance()
                        self.tts.speak_text(text)
                        results = self.tts.end_utterance()

                    for result in results:
                        # Add audio to existing WAV file
                        if isinstance(result, AudioResult):
                            if not wav_params_set:
                                wav_file.setframerate(result.sample_rate_hz)
                                wav_file.setsampwidth(result.sample_width_bytes)
                                wav_file.setnchannels(result.num_channels)
                                wav_params_set = True

                            wav_file.writeframes(result.audio_bytes)
                except Exception as e:
                    if not wav_params_set:
                        # Set default parameters so exception can propagate
                        wav_file.setframerate(22050)
                        wav_file.setsampwidth(2)
                        wav_file.setnchannels(1)

                    raise e

            wav_bytes = wav_io.getvalue()

        return wav_bytes


# TODO manually check gender of each voice and add below
Mimic3TTSPluginConfig = {
    'af-za': [
        {'display_name': 'Google-Nwu - 7214',
         'gender': '',
         'speaker': '7214',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8963',
         'gender': '',
         'speaker': '8963',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 7130',
         'gender': '',
         'speaker': '7130',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8924',
         'gender': '',
         'speaker': '8924',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8148',
         'gender': '',
         'speaker': '8148',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 1919',
         'gender': '',
         'speaker': '1919',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 2418',
         'gender': '',
         'speaker': '2418',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 6590',
         'gender': '',
         'speaker': '6590',
         'voice': 'af_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 0184',
         'gender': '',
         'speaker': '0184',
         'voice': 'af_ZA/google-nwu_low'}
    ],
    'bn': [
        {'display_name': 'Multi - Rm',
         'gender': '',
         'speaker': 'rm',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 03042',
         'gender': '',
         'speaker': '03042',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 00737',
         'gender': '',
         'speaker': '00737',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 01232',
         'gender': '',
         'speaker': '01232',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 02194',
         'gender': '',
         'speaker': '02194',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 3108',
         'gender': '',
         'speaker': '3108',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 3713',
         'gender': '',
         'speaker': '3713',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 1010',
         'gender': '',
         'speaker': '1010',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 00779',
         'gender': '',
         'speaker': '00779',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 9169',
         'gender': '',
         'speaker': '9169',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 4046',
         'gender': '',
         'speaker': '4046',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 5958',
         'gender': '',
         'speaker': '5958',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 01701',
         'gender': '',
         'speaker': '01701',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 4811',
         'gender': '',
         'speaker': '4811',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 0834',
         'gender': '',
         'speaker': '0834',
         'voice': 'bn/multi_low'},
        {'display_name': 'Multi - 3958',
         'gender': '',
         'speaker': '3958',
         'voice': 'bn/multi_low'}
    ],
    'de-de': [
        {'display_name': 'Thorsten',
         'gender': '',
         'speaker': 'default',
         'voice': 'de_DE/thorsten_low'},
        {'display_name': 'Thorsten-Emotion - Amused',
         'gender': '',
         'speaker': 'amused',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Angry',
         'gender': '',
         'speaker': 'angry',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Disgusted',
         'gender': '',
         'speaker': 'disgusted',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Drunk',
         'gender': '',
         'speaker': 'drunk',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Neutral',
         'gender': '',
         'speaker': 'neutral',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Sleepy',
         'gender': '',
         'speaker': 'sleepy',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Surprised',
         'gender': '',
         'speaker': 'surprised',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'Thorsten-Emotion - Whisper',
         'gender': '',
         'speaker': 'whisper',
         'voice': 'de_DE/thorsten-emotion_low'},
        {'display_name': 'M-Ailabs - Ramona Deininger',
         'gender': '',
         'speaker': 'ramona_deininger',
         'voice': 'de_DE/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Karlsson',
         'gender': '',
         'speaker': 'karlsson',
         'voice': 'de_DE/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Rebecca Braunert Plunkett',
         'gender': '',
         'speaker': 'rebecca_braunert_plunkett',
         'voice': 'de_DE/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Eva K',
         'gender': '',
         'speaker': 'eva_k',
         'voice': 'de_DE/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Angela Merkel',
         'gender': '',
         'speaker': 'angela_merkel',
         'voice': 'de_DE/m-ailabs_low'}
    ],
    'el-gr': [
        {'display_name': 'Rapunzelina',
         'gender': '',
         'speaker': 'default',
         'voice': 'el_GR/rapunzelina_low'}
    ],
    'en-gb': [
        {'display_name': 'Apope',
         'gender': 'male',
         'speaker': 'default',
         'voice': 'en_UK/apope_low'}
    ],
    'en-us': [
        {'display_name': 'Cmu-Arctic - Slt',
         'gender': 'female',
         'speaker': 'slt',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Awb',
         'gender': 'male',
         'speaker': 'awb',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Rms',
         'gender': 'male',
         'speaker': 'rms',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Ksp',
         'gender': 'male',
         'speaker': 'ksp',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Clb',
         'gender': 'female',
         'speaker': 'clb',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Aew',
         'gender': 'male',
         'speaker': 'aew',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Bdl',
         'gender': 'male',
         'speaker': 'bdl',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Cmu-Arctic - Lnh',
         'gender': 'female',
         'speaker': 'lnh',
         'voice': 'en_US/cmu-arctic_low'},
        {'display_name': 'Hifi-Tts - 9017',
         'gender': 'male',
         'speaker': '9017',
         'voice': 'en_US/hifi-tts_low'},
        {'display_name': 'Hifi-Tts - 6097',
         'gender': 'male',
         'speaker': '6097',
         'voice': 'en_US/hifi-tts_low'},
        {'display_name': 'Hifi-Tts - 92',
         'gender': 'female',
         'speaker': '92',
         'voice': 'en_US/hifi-tts_low'},
        {'display_name': 'Ljspeech',
         'gender': 'female',
         'speaker': 'default',
         'voice': 'en_US/ljspeech_low'},
        {'display_name': 'M-Ailabs - Elliot Miller',
         'gender': 'male',
         'speaker': 'elliot_miller',
         'voice': 'en_US/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Judy Bieber',
         'gender': 'female',
         'speaker': 'judy_bieber',
         'voice': 'en_US/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Mary Ann',
         'gender': 'female',
         'speaker': 'mary_ann',
         'voice': 'en_US/m-ailabs_low'},
        {'display_name': 'Vctk - P239',
         'gender': '',
         'speaker': 'p239',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P236',
         'gender': '',
         'speaker': 'p236',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P264',
         'gender': '',
         'speaker': 'p264',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P250',
         'gender': '',
         'speaker': 'p250',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P259',
         'gender': '',
         'speaker': 'p259',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P247',
         'gender': '',
         'speaker': 'p247',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P261',
         'gender': '',
         'speaker': 'p261',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P263',
         'gender': '',
         'speaker': 'p263',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P283',
         'gender': '',
         'speaker': 'p283',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P274',
         'gender': '',
         'speaker': 'p274',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P286',
         'gender': '',
         'speaker': 'p286',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P276',
         'gender': '',
         'speaker': 'p276',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P270',
         'gender': '',
         'speaker': 'p270',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P281',
         'gender': '',
         'speaker': 'p281',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P277',
         'gender': '',
         'speaker': 'p277',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P231',
         'gender': '',
         'speaker': 'p231',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P238',
         'gender': '',
         'speaker': 'p238',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P271',
         'gender': '',
         'speaker': 'p271',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P257',
         'gender': '',
         'speaker': 'p257',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P273',
         'gender': '',
         'speaker': 'p273',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P284',
         'gender': '',
         'speaker': 'p284',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P329',
         'gender': '',
         'speaker': 'p329',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P361',
         'gender': '',
         'speaker': 'p361',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P287',
         'gender': '',
         'speaker': 'p287',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P360',
         'gender': '',
         'speaker': 'p360',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P374',
         'gender': '',
         'speaker': 'p374',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P376',
         'gender': '',
         'speaker': 'p376',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P310',
         'gender': '',
         'speaker': 'p310',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P304',
         'gender': '',
         'speaker': 'p304',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P340',
         'gender': '',
         'speaker': 'p340',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P347',
         'gender': '',
         'speaker': 'p347',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P330',
         'gender': '',
         'speaker': 'p330',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P308',
         'gender': '',
         'speaker': 'p308',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P314',
         'gender': '',
         'speaker': 'p314',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P317',
         'gender': '',
         'speaker': 'p317',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P339',
         'gender': '',
         'speaker': 'p339',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P311',
         'gender': '',
         'speaker': 'p311',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P294',
         'gender': '',
         'speaker': 'p294',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P305',
         'gender': '',
         'speaker': 'p305',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P266',
         'gender': '',
         'speaker': 'p266',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P335',
         'gender': '',
         'speaker': 'p335',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P334',
         'gender': '',
         'speaker': 'p334',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P318',
         'gender': '',
         'speaker': 'p318',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P323',
         'gender': '',
         'speaker': 'p323',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P351',
         'gender': '',
         'speaker': 'p351',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P333',
         'gender': '',
         'speaker': 'p333',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P313',
         'gender': '',
         'speaker': 'p313',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P316',
         'gender': '',
         'speaker': 'p316',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P244',
         'gender': '',
         'speaker': 'p244',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P307',
         'gender': '',
         'speaker': 'p307',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P363',
         'gender': '',
         'speaker': 'p363',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P336',
         'gender': '',
         'speaker': 'p336',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P312',
         'gender': '',
         'speaker': 'p312',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P267',
         'gender': '',
         'speaker': 'p267',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P297',
         'gender': '',
         'speaker': 'p297',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P275',
         'gender': '',
         'speaker': 'p275',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P295',
         'gender': '',
         'speaker': 'p295',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P288',
         'gender': '',
         'speaker': 'p288',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P258',
         'gender': '',
         'speaker': 'p258',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P301',
         'gender': '',
         'speaker': 'p301',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P232',
         'gender': '',
         'speaker': 'p232',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P292',
         'gender': '',
         'speaker': 'p292',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P272',
         'gender': '',
         'speaker': 'p272',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P278',
         'gender': '',
         'speaker': 'p278',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P280',
         'gender': '',
         'speaker': 'p280',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P341',
         'gender': '',
         'speaker': 'p341',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P268',
         'gender': '',
         'speaker': 'p268',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P298',
         'gender': '',
         'speaker': 'p298',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P299',
         'gender': '',
         'speaker': 'p299',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P279',
         'gender': '',
         'speaker': 'p279',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P285',
         'gender': '',
         'speaker': 'p285',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P326',
         'gender': '',
         'speaker': 'p326',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P300',
         'gender': '',
         'speaker': 'p300',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - S5',
         'gender': '',
         'speaker': 's5',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P230',
         'gender': '',
         'speaker': 'p230',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P254',
         'gender': '',
         'speaker': 'p254',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P269',
         'gender': '',
         'speaker': 'p269',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P293',
         'gender': '',
         'speaker': 'p293',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P252',
         'gender': '',
         'speaker': 'p252',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P345',
         'gender': '',
         'speaker': 'p345',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P262',
         'gender': '',
         'speaker': 'p262',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P243',
         'gender': '',
         'speaker': 'p243',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P227',
         'gender': '',
         'speaker': 'p227',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P343',
         'gender': '',
         'speaker': 'p343',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P255',
         'gender': '',
         'speaker': 'p255',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P229',
         'gender': '',
         'speaker': 'p229',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P240',
         'gender': '',
         'speaker': 'p240',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P248',
         'gender': '',
         'speaker': 'p248',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P253',
         'gender': '',
         'speaker': 'p253',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P233',
         'gender': '',
         'speaker': 'p233',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P228',
         'gender': '',
         'speaker': 'p228',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P251',
         'gender': '',
         'speaker': 'p251',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P282',
         'gender': '',
         'speaker': 'p282',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P246',
         'gender': '',
         'speaker': 'p246',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P234',
         'gender': '',
         'speaker': 'p234',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P226',
         'gender': '',
         'speaker': 'p226',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P260',
         'gender': '',
         'speaker': 'p260',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P245',
         'gender': '',
         'speaker': 'p245',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P241',
         'gender': '',
         'speaker': 'p241',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P303',
         'gender': '',
         'speaker': 'p303',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P265',
         'gender': '',
         'speaker': 'p265',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P306',
         'gender': '',
         'speaker': 'p306',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P237',
         'gender': '',
         'speaker': 'p237',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P249',
         'gender': '',
         'speaker': 'p249',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P256',
         'gender': '',
         'speaker': 'p256',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P302',
         'gender': '',
         'speaker': 'p302',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P364',
         'gender': '',
         'speaker': 'p364',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P225',
         'gender': '',
         'speaker': 'p225',
         'voice': 'en_US/vctk_low'},
        {'display_name': 'Vctk - P362',
         'gender': '',
         'speaker': 'p362',
         'voice': 'en_US/vctk_low'}
    ],
    'es-es': [
        {'display_name': 'Carlfm',
         'gender': '',
         'speaker': 'default',
         'voice': 'es_ES/carlfm_low'},
        {'display_name': 'M-Ailabs - Tux',
         'gender': '',
         'speaker': 'tux',
         'voice': 'es_ES/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Victor Villarraza',
         'gender': '',
         'speaker': 'victor_villarraza',
         'voice': 'es_ES/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Karen Savage',
         'gender': '',
         'speaker': 'karen_savage',
         'voice': 'es_ES/m-ailabs_low'}
    ],
    'fa': [
        {'display_name': 'Haaniye',
         'gender': '',
         'speaker': 'default',
         'voice': 'fa/haaniye_low'}
    ],
    'fi-fi': [
        {'display_name': 'Harri-Tapani-Ylilammi',
         'gender': '',
         'speaker': 'default',
         'voice': 'fi_FI/harri-tapani-ylilammi_low'}
    ],
    'fr-fr': [
        {'display_name': 'M-Ailabs - Ezwa',
         'gender': '',
         'speaker': 'ezwa',
         'voice': 'fr_FR/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Nadine Eckert Boulet',
         'gender': '',
         'speaker': 'nadine_eckert_boulet',
         'voice': 'fr_FR/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Bernard',
         'gender': '',
         'speaker': 'bernard',
         'voice': 'fr_FR/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Zeckou',
         'gender': '',
         'speaker': 'zeckou',
         'voice': 'fr_FR/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Gilles G Le Blanc',
         'gender': '',
         'speaker': 'gilles_g_le_blanc',
         'voice': 'fr_FR/m-ailabs_low'},
        {'display_name': 'Siwis',
         'gender': '',
         'speaker': 'default',
         'voice': 'fr_FR/siwis_low'},
        {'display_name': 'Tom',
         'gender': '',
         'speaker': 'default',
         'voice': 'fr_FR/tom_low'}
    ],
    'gu-in': [
        {'display_name': 'Cmu-Indic - Cmu Indic Guj Dp',
         'gender': '',
         'speaker': 'cmu_indic_guj_dp',
         'voice': 'gu_IN/cmu-indic_low'},
        {'display_name': 'Cmu-Indic - Cmu Indic Guj Ad',
         'gender': '',
         'speaker': 'cmu_indic_guj_ad',
         'voice': 'gu_IN/cmu-indic_low'},
        {'display_name': 'Cmu-Indic - Cmu Indic Guj Kt',
         'gender': '',
         'speaker': 'cmu_indic_guj_kt',
         'voice': 'gu_IN/cmu-indic_low'}
    ],
    'ha-ne': [
        {'display_name': 'Openbible',
         'gender': '',
         'speaker': 'default',
         'voice': 'ha_NE/openbible_low'}
    ],
    'hu-hu': [
        {'display_name': 'Diana-Majlinger',
         'gender': '',
         'speaker': 'default',
         'voice': 'hu_HU/diana-majlinger_low'}
    ],
    'it-it': [
        {'display_name': 'Riccardo-Fasol',
         'gender': '',
         'speaker': 'default',
         'voice': 'it_IT/riccardo-fasol_low'},
        {'display_name': 'Mls - 1595',
         'gender': '',
         'speaker': '1595',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4974',
         'gender': '',
         'speaker': '4974',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4998',
         'gender': '',
         'speaker': '4998',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 6807',
         'gender': '',
         'speaker': '6807',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 1989',
         'gender': '',
         'speaker': '1989',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 2033',
         'gender': '',
         'speaker': '2033',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 2019',
         'gender': '',
         'speaker': '2019',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 659',
         'gender': '',
         'speaker': '659',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4649',
         'gender': '',
         'speaker': '4649',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 9772',
         'gender': '',
         'speaker': '9772',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 1725',
         'gender': '',
         'speaker': '1725',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 10446',
         'gender': '',
         'speaker': '10446',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 6348',
         'gender': '',
         'speaker': '6348',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 6001',
         'gender': '',
         'speaker': '6001',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 9185',
         'gender': '',
         'speaker': '9185',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8842',
         'gender': '',
         'speaker': '8842',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8828',
         'gender': '',
         'speaker': '8828',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 12428',
         'gender': '',
         'speaker': '12428',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8181',
         'gender': '',
         'speaker': '8181',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 7440',
         'gender': '',
         'speaker': '7440',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8207',
         'gender': '',
         'speaker': '8207',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 277',
         'gender': '',
         'speaker': '277',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 5421',
         'gender': '',
         'speaker': '5421',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 12804',
         'gender': '',
         'speaker': '12804',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4705',
         'gender': '',
         'speaker': '4705',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 7936',
         'gender': '',
         'speaker': '7936',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 844',
         'gender': '',
         'speaker': '844',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 6299',
         'gender': '',
         'speaker': '6299',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 644',
         'gender': '',
         'speaker': '644',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8384',
         'gender': '',
         'speaker': '8384',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 1157',
         'gender': '',
         'speaker': '1157',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 7444',
         'gender': '',
         'speaker': '7444',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 643',
         'gender': '',
         'speaker': '643',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4971',
         'gender': '',
         'speaker': '4971',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 4975',
         'gender': '',
         'speaker': '4975',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 6744',
         'gender': '',
         'speaker': '6744',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 8461',
         'gender': '',
         'speaker': '8461',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 7405',
         'gender': '',
         'speaker': '7405',
         'voice': 'it_IT/mls_low'},
        {'display_name': 'Mls - 5010',
         'gender': '',
         'speaker': '5010',
         'voice': 'it_IT/mls_low'}
    ],
    'jv-id': [
        {'display_name': 'Google-Gmu - 07875',
         'gender': '',
         'speaker': '07875',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 05522',
         'gender': '',
         'speaker': '05522',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 03424',
         'gender': '',
         'speaker': '03424',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 06510',
         'gender': '',
         'speaker': '06510',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 03314',
         'gender': '',
         'speaker': '03314',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 03187',
         'gender': '',
         'speaker': '03187',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 07638',
         'gender': '',
         'speaker': '07638',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 06207',
         'gender': '',
         'speaker': '06207',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 08736',
         'gender': '',
         'speaker': '08736',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04679',
         'gender': '',
         'speaker': '04679',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 01392',
         'gender': '',
         'speaker': '01392',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 05540',
         'gender': '',
         'speaker': '05540',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 05219',
         'gender': '',
         'speaker': '05219',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 00027',
         'gender': '',
         'speaker': '00027',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 00264',
         'gender': '',
         'speaker': '00264',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 09724',
         'gender': '',
         'speaker': '09724',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04588',
         'gender': '',
         'speaker': '04588',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 09039',
         'gender': '',
         'speaker': '09039',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04285',
         'gender': '',
         'speaker': '04285',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 05970',
         'gender': '',
         'speaker': '05970',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 08305',
         'gender': '',
         'speaker': '08305',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04982',
         'gender': '',
         'speaker': '04982',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 08002',
         'gender': '',
         'speaker': '08002',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 06080',
         'gender': '',
         'speaker': '06080',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 07765',
         'gender': '',
         'speaker': '07765',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 02326',
         'gender': '',
         'speaker': '02326',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 03727',
         'gender': '',
         'speaker': '03727',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04175',
         'gender': '',
         'speaker': '04175',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 06383',
         'gender': '',
         'speaker': '06383',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 02884',
         'gender': '',
         'speaker': '02884',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 06941',
         'gender': '',
         'speaker': '06941',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 08178',
         'gender': '',
         'speaker': '08178',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 00658',
         'gender': '',
         'speaker': '00658',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 04715',
         'gender': '',
         'speaker': '04715',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 05667',
         'gender': '',
         'speaker': '05667',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 01519',
         'gender': '',
         'speaker': '01519',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 07335',
         'gender': '',
         'speaker': '07335',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 02059',
         'gender': '',
         'speaker': '02059',
         'voice': 'jv_ID/google-gmu_low'},
        {'display_name': 'Google-Gmu - 01932',
         'gender': '',
         'speaker': '01932',
         'voice': 'jv_ID/google-gmu_low'}
    ],
    'ko-ko': [
        {'display_name': 'Kss',
         'gender': '',
         'speaker': 'default',
         'voice': 'ko_KO/kss_low'}
    ],
    'ne-np': [
        {'display_name': 'Ne-Google - 0546',
         'gender': '',
         'speaker': '0546',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 3614',
         'gender': '',
         'speaker': '3614',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 2099',
         'gender': '',
         'speaker': '2099',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 3960',
         'gender': '',
         'speaker': '3960',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 6834',
         'gender': '',
         'speaker': '6834',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 7957',
         'gender': '',
         'speaker': '7957',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 6329',
         'gender': '',
         'speaker': '6329',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 9407',
         'gender': '',
         'speaker': '9407',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 6587',
         'gender': '',
         'speaker': '6587',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 0258',
         'gender': '',
         'speaker': '0258',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 2139',
         'gender': '',
         'speaker': '2139',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 5687',
         'gender': '',
         'speaker': '5687',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 0283',
         'gender': '',
         'speaker': '0283',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 3997',
         'gender': '',
         'speaker': '3997',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 3154',
         'gender': '',
         'speaker': '3154',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 0883',
         'gender': '',
         'speaker': '0883',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 2027',
         'gender': '',
         'speaker': '2027',
         'voice': 'ne_NP/ne-google_low'},
        {'display_name': 'Ne-Google - 0649',
         'gender': '',
         'speaker': '0649',
         'voice': 'ne_NP/ne-google_low'}
    ],
    'nl': [
        {'display_name': 'Bart-De-Leeuw',
         'gender': '',
         'speaker': 'default',
         'voice': 'nl/bart-de-leeuw_low'},
        {'display_name': 'Flemishguy',
         'gender': '',
         'speaker': 'default',
         'voice': 'nl/flemishguy_low'},
        {'display_name': 'Nathalie',
         'gender': '',
         'speaker': 'default',
         'voice': 'nl/nathalie_low'},
        {'display_name': 'Pmk',
         'gender': '',
         'speaker': 'default',
         'voice': 'nl/pmk_low'},
        {'display_name': 'Rdh',
         'gender': '',
         'speaker': 'default',
         'voice': 'nl/rdh_low'}
    ],
    'pl-pl': [
        {'display_name': 'M-Ailabs - Piotr Nater',
         'gender': '',
         'speaker': 'piotr_nater',
         'voice': 'pl_PL/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Nina Brown',
         'gender': '',
         'speaker': 'nina_brown',
         'voice': 'pl_PL/m-ailabs_low'}
    ],
    'ru-ru': [
        {'display_name': 'Multi - Hajdurova',
         'gender': '',
         'speaker': 'hajdurova',
         'voice': 'ru_RU/multi_low'},
        {'display_name': 'Multi - Minaev',
         'gender': '',
         'speaker': 'minaev',
         'voice': 'ru_RU/multi_low'},
        {'display_name': 'Multi - Nikolaev',
         'gender': '',
         'speaker': 'nikolaev',
         'voice': 'ru_RU/multi_low'}
    ],
    'sw': [
        {'display_name': 'Lanfrica',
         'gender': '',
         'speaker': 'default',
         'voice': 'sw/lanfrica_low'}
    ],
    'te-in': [
        {'display_name': 'Cmu-Indic - Ss',
         'gender': '',
         'speaker': 'ss',
         'voice': 'te_IN/cmu-indic_low'},
        {'display_name': 'Cmu-Indic - Sk',
         'gender': '',
         'speaker': 'sk',
         'voice': 'te_IN/cmu-indic_low'},
        {'display_name': 'Cmu-Indic - Kpn',
         'gender': '',
         'speaker': 'kpn',
         'voice': 'te_IN/cmu-indic_low'}
    ],
    'tn-za': [
        {'display_name': 'Google-Nwu - 1932',
         'gender': '',
         'speaker': '1932',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 0045',
         'gender': '',
         'speaker': '0045',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 3342',
         'gender': '',
         'speaker': '3342',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 4850',
         'gender': '',
         'speaker': '4850',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 6206',
         'gender': '',
         'speaker': '6206',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 3629',
         'gender': '',
         'speaker': '3629',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 9061',
         'gender': '',
         'speaker': '9061',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 6116',
         'gender': '',
         'speaker': '6116',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 7674',
         'gender': '',
         'speaker': '7674',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 0378',
         'gender': '',
         'speaker': '0378',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 5628',
         'gender': '',
         'speaker': '5628',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8333',
         'gender': '',
         'speaker': '8333',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8512',
         'gender': '',
         'speaker': '8512',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 0441',
         'gender': '',
         'speaker': '0441',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 6459',
         'gender': '',
         'speaker': '6459',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 4506',
         'gender': '',
         'speaker': '4506',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 7866',
         'gender': '',
         'speaker': '7866',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8532',
         'gender': '',
         'speaker': '8532',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 2839',
         'gender': '',
         'speaker': '2839',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 7896',
         'gender': '',
         'speaker': '7896',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 1498',
         'gender': '',
         'speaker': '1498',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 1483',
         'gender': '',
         'speaker': '1483',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 8914',
         'gender': '',
         'speaker': '8914',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 6234',
         'gender': '',
         'speaker': '6234',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 9365',
         'gender': '',
         'speaker': '9365',
         'voice': 'tn_ZA/google-nwu_low'},
        {'display_name': 'Google-Nwu - 7693',
         'gender': '',
         'speaker': '7693',
         'voice': 'tn_ZA/google-nwu_low'}
    ],
    'uk-uk': [
        {'display_name': 'M-Ailabs - Obruchov',
         'gender': '',
         'speaker': 'obruchov',
         'voice': 'uk_UK/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Shepel',
         'gender': '',
         'speaker': 'shepel',
         'voice': 'uk_UK/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Loboda',
         'gender': '',
         'speaker': 'loboda',
         'voice': 'uk_UK/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Miskun',
         'gender': '',
         'speaker': 'miskun',
         'voice': 'uk_UK/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Sumska',
         'gender': '',
         'speaker': 'sumska',
         'voice': 'uk_UK/m-ailabs_low'},
        {'display_name': 'M-Ailabs - Pysariev',
         'gender': '',
         'speaker': 'pysariev',
         'voice': 'uk_UK/m-ailabs_low'}
    ],
    'vi-vn': [
        {'display_name': 'Vais1000',
         'gender': '',
         'speaker': 'default',
         'voice': 'vi_VN/vais1000_low'}
    ],
    'yo': [
        {'display_name': 'Openbible',
         'gender': '',
         'speaker': 'default',
         'voice': 'yo/openbible_low'}
    ]
}
